### PR TITLE
[Fixed] Long text in clipboard

### PR DESCRIPTION
**Pull request by Kristinita**
### 1. Settings

For example, I select code:

```json
"kristina_monamour": {
    "caption": "Color Scheme Units: Show Scope Name",
    "call": "sublime.show_scope_name_and_styles"
},
```

I run `paste_repeater` command.

### 2. Behavior before pull request

My symbols don't fit in input panel:

Input panel

### 3. Behavior after pull request

Clipboard content don't paste into input panel.

Right input panel

Thanks.

### CODE REVIEW

**Comment by philsinatra** [comment]
This change would disable the preview text. Technically the change is not fixing a problem, it's more of a display preference for situations when all of the copied text doesn't fit in the preview. I think a truncated preview is better than none.

**Comment by Kristinita** [comment]
@philsinatra ,

>  I think a truncated preview is better than none.

If user select long text, user don't see introduce numbers.

Thanks.

**Comment by philsinatra** [comment]
@Kristinita Okay I see, you mean when the Sublime window itself is smaller the string is the only part that's visible. Good catch. I'll work in a conditional and incorporate a fix. Thanks 😀

**Comment by philsinatra** [comment]
@Kristinita [Your fix](https://github.com/philsinatra/SublimePasteRepeater/commit/4f1928a84b2e8aff3b2428dbb3592c53d210fbd3) is in. PackageControl should find the update within a few hours and push it out.

Thanks for contributing.

**Pull request closed without merging**
